version: '3.8'
services:
  web:
    build: .
    env_file:
      - .env.sample
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - SECRET_KEY_BASE_DUMMY=1 # not using the secret key, ignore it
