version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - public_assets:/rails/public/assets
    env_file:
      - .env

volumes:
  public_assets:
