name: "build"
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
      DATA_REPO_TOKEN: ${{ secrets.DEPLOY_BOT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout data repo
        uses: actions/checkout@v4
        with:
          repository: kaigaiijuch/website_data
          path: data
          token: ${{ env.DATA_REPO_TOKEN }}
      - name: setup docker
        run: docker compose -f docker-compose-build.yml build
      - name: build static html files
        run: docker compose -f docker-compose-build.yml run web bin/build && ls -lah public
      - name: save version file
        run: |
          echo "website: ${{github.event.after}}" > public/version.txt
          echo "website_data: $(cd data && git show -s --format=%H)" >> public/version.txt
          cat public/version.txt
      - name: upload static html files as a artifact
        uses: actions/upload-artifact@v4
        with:
          name: public_files_${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
          path: |
            public
      - name: ping release trigger
        # note: github.event.head_commit.message looks only available in push event
        if: contains(github.event.head_commit.message, vars.RELEASE_TRRIGER_MESSAGE)
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          commit_message=$(echo ${COMMIT_MESSAGE} | head -n1)
          curl --fail-with-body -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_BOT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/kaigaiijuch/release/dispatches \
            -d "{\"event_type\":\"run_release\", \"client_payload\": {
              \"commit_message\": \"${commit_message}\",
              \"commit_url\": \"https://github.com/kaigaiijuch/website/commits/${{ github.event.after }}\"
              }
            }"
