name: "build"
on:
  push:
    branches: [ "main" ]
  pull-request: # temporary
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
      DATA_REPO_TOKEN: ${{ secrets.DEPLOY_BOT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout data repo
        uses: actions/checkout@v4
        with:
          repository: kaigaiijuch/website_data
          path: data
          token: ${{ env.DATA_REPO_TOKEN }}
      - name: debug version
        run: bin/version
      - name: setup docker
        run: docker compose -f docker-compose-build.yml build
      - name: build static html files
        run: docker compose -f docker-compose-build.yml run web bin/build && ls -lah public
      - name: debug version
        run: docker compose -f docker-compose-build.yml run web bin/version
      - name: upload static html files as a artifact
        uses: actions/upload-artifact@v4
        with:
          name: public_files
          path: |
            public
