name: "build"
on:
  push:
    branches: [ "main" ]
  pull_request: # temporary
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout data repo
        uses: actions/checkout@v4
        with:
          repository: kaigaiijuch/website_data
          ref: main
          path: data
          token: ${{ secrets.GH_TOKEN }}
      - name: setup docker
        run: docker compose -f docker-compose-build.yml build
      - name: run test
        run: docker compose -f docker-compose-build.yml run web bin/rake
      - name: build static html
        run: docker compose -f docker-compose-build.yml run web bin/build
      - name: Archive static html artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: |
            public
