name: "build"
on:
  push:
    branches: [ "main" ]
  pull_request: # temporary
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout data repo
        uses: actions/checkout@v4
        with:
          repository: kaigaiijuch/website_data
          path: data
          token: ${{ secrets.DATA_REPO_TOKEN }}
      - name: setup docker
        run: docker compose -f docker-compose-build.yml build
      ## no test for build artifact
      # - name: run test
      #   run: docker compose -f docker-compose-build.yml run web bin/rake
      - name: debug
        run: touch public/hote
      - name: debug2
        run: ls -lah public
      - name: debug3
        run: docker compose -f docker-compose-build.yml run web ls -lah public/ && touch public/aaa && ls -lah public/
      - name: build static html files
        run: docker compose -f docker-compose-build.yml run -v public:/rails/public web bin/build
      - name: upload static html files as a artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact
          path: |
            public
