name: Check ERD

on: [pull_request]

jobs:
  check_erd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check that ERD is up-to-dated
      run: |
        git fetch origin master:refs/remotes/origin/master
        git diff --name-only "feature/my-branch..origin/master"
        if [[ $(git diff remotes/origin/${{ github.base_ref }} --name-only | grep db/schema.rb) ]]; then
          git diff remotes/origin/${{ github.base_ref }} --name-only | grep docs/erd.png || exit 1
        fi
