name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      TRACE: ${{ vars.TRACE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup docker
        run: docker compose -f docker-compose-ci.yml build
      - name: run test
        run: docker compose -f docker-compose-ci.yml run -e RAILS_ENV=$RAILS_ENV -e TRACE=$TRACE web bin/rake
