name: "CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup docker
        run: docker compose -f docker-compose-ci.yml build
      - name: run test
        run: docker compose -f docker-compose-ci.yml run web bin/rake
