name: "fetch_rss"
on:
  repository_dispatch:
    types: [fetch_rss]
  schedule:
    # workaround: in some reason, the rss looks not latest version (cache?) therefore try several times
    - cron:  '1,25,45 21 * * 1' # target for JST 6:01, 6:25, 6:45 on Monday
    - cron:  '55 20 * * 1' # target for JST 5:45 (somehow it always run with 20 mins delay)
jobs:
  fetch_rss:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
      DATA_REPO_TOKEN: ${{ secrets.DEPLOY_BOT_TOKEN }}
      SPOTIFY_FOR_PODCASTERS_RSS_URL: ${{ vars.SPOTIFY_FOR_PODCASTERS_RSS_URL }}
      GITHUB_TOKEN: ${{ secrets.DEPLOY_BOT_TOKEN }}
      TRACE: ${{ vars.TRACE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # https://github.com/ad-m/github-push-action#example-workflow-file
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Checkout data repo
        uses: actions/checkout@v4
        with:
          repository: kaigaiijuch/website_data
          path: data
          token: ${{ env.DATA_REPO_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.name "${{ vars.GIT_USER_NAME }}"
          git config --global user.email "${{ vars.GIT_USER_EMAIL }}"
          cd data
          git config --global user.name "${{ vars.GIT_USER_NAME }}"
          git config --global user.email "${{ vars.GIT_USER_EMAIL }}"
          cd ..
      - name: setup docker
        run: docker compose -e TRACE=$TRACE -f docker-compose-build.yml build
      - name: fetch data
        run: docker compose -e TRACE=$TRACE -f docker-compose-build.yml run web bin/rake data:fetch_feeds_spotify_for_podcasters["$SPOTIFY_FOR_PODCASTERS_RSS_URL"]
      - name: commit data if it's changes
        run: |
          if yes 2>/dev/null | bin/data/commit > /dev/null 2>&1 ; then
            echo "run_build=true" >> "$GITHUB_ENV"
          else
            echo "run_build=false" >> "$GITHUB_ENV"
          fi
      - name: commit
        if: env.run_build == 'true'
        env:
          RELEASE_TRRIGER_MESSAGE: ${{ vars.RELEASE_TRRIGER_MESSAGE }}
          RELEASE_AUTOMERGE_LABEL: ${{ vars.RELEASE_AUTOMERGE_LABEL }}
        run: |
          git commit --allow-empty -m "${RELEASE_TRRIGER_MESSAGE} ${RELEASE_AUTOMERGE_LABEL} fetch rss feeds at '$(date)'"
      - name: push
        uses: ad-m/github-push-action@master
        if: env.run_build == 'true'
        with:
          # Push from Action does not trigger subsequent action: https://github.com/orgs/community/discussions/25702
          github_token: ${{ secrets.FETCH_RSS_PUSH_PAT }}
          branch: ${{ github.ref }}
